### ISSUE TITLE
Error loading on Gentoo

### ISSUE THREAD

**Issue by jlax47** [axch/test-manager#2]
I'm having a problem using the test-manager software on my my schools CS servers. The problem is fairly obvious in that I don't have read permission on the directory/file it's looking to load, but I'm not sure how to work around the problem.

```
MIT/GNU Scheme running under GNU/Linux
Type `^C' (control-C) followed by `H' to obtain information about interrupts.

Copyright (C) 2014 Massachusetts Institute of Technology
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Image saved on Tuesday April 7, 2015 at 7:32:33 PM
  Release 9.2 || Microcode 15.3 || Runtime 15.7 || SF 4.41 || LIAR/x86-64 4.118 || Edwin 3.116

1 ]=> (load "load")

;Loading "load.scm"...
;  Loading "portability.scm"...
;    Loading "mitscheme-conditions.scm"... done
;Unable to determine type of file "/usr/local/lib/mit-scheme-x86-64/sos/make" because: Permission denied.
;To continue, call RESTART with an option number:
; (RESTART 3) => Try to determine type of the same file again.
; (RESTART 2) => Try to determine type of a different file.
; (RESTART 1) => Return to read-eval-print level 1.
```

Here's an `ls -al` of the file:

```
$ ls -al /usr/local/lib/mit-scheme-x86-64/sos/make
ls: cannot access /usr/local/lib/mit-scheme-x86-64/sos/make: Permission denied
```

Here's an `ls -al` of the closest directory I have access to:

```
$ ls -al /usr/local/lib/mit-scheme-x86-64         
total 28764
drwxr-xr-x 15 root root     4096 Apr  7 19:34 .
drwxr-xr-x  4 root root     4096 Apr  7 19:27 ..
-rw-r--r--  1 root root 20985816 Apr  7 19:34 all.com
drwx------  9 root root     4096 Apr  7 19:34 compiler
drwx------  2 root root     4096 Apr  7 19:34 cref
drwx------  7 root root     4096 Apr  7 19:21 doc
drwx------  2 root root     4096 Apr  7 19:34 edwin
drwx------  2 root root     4096 Apr  7 19:34 ffi
drwx------  2 root root     4096 Apr  7 19:34 imail
drwx------  2 root root     4096 Apr  7 19:34 lib
-rw-r--r--  1 root root     3783 May 17  2014 mit-scheme.h
-rw-r--r--  1 root root     4019 Apr  7 19:34 optiondb.scm
drwx------  2 root root    12288 Apr  7 19:34 runtime
-rw-r--r--  1 root root  8381224 Apr  7 19:34 runtime.com
drwx------  2 root root     4096 Apr  7 19:34 sf
-rw-r--r--  1 root root      417 Apr  7 19:19 shim-config.scm
drwx------  2 root root     4096 Apr  7 19:34 sos
drwx------  2 root root     4096 Apr  7 19:34 ssp
drwx------  2 root root     4096 Apr  7 19:34 star-parser
drwx------  2 root root     4096 Apr  7 19:34 xml
```

I can probably get around it by asking if the CS IT department will open the permissions so I can read that file. But I was just curious if the problem is in an explicit call you are making to load, or if it's in one of the `use-modules` calls you make.

Either way, thank you for the test suite. This is my first time doing anything in scheme and it's a whole lot easier refactoring the code I've produced when I can run some tests to know I haven't broken anything.

**Comment by jlax47** [comment]
Of course after looking at it a bit more, I was able to trace the problem down to a specific call.

```
(load-option 'sos)
```

I'll open a ticket with my help desk and see if they can make the changes so I can read the file. Also it looks like the server admins built it from source, so it's not a specific Gentoo thing.

**Comment by axch** [comment]
Happy to be of use :)  You're right, this is an issue with the installation of MIT Scheme on that system.  Based on what you said, I would expect `(load-option 'sos)` not to work there without some permissions changes, regardless of the rest of `test-manager`.  Just so you know, `sos` is the Scheme Object System, which provides an object-oriented-style class, inheritance and generic function mechanism that `test-manager` uses.
